{% set name = "Directory-Tree" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rahulbordoloi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 620d8d8cfaf07903379338d3e9b9de58da37a85ae332e92389bb8d98e11ca2d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - directory_tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rahulbordoloi/Directory-Tree/
  summary: Python Utility Package that displays out the Tree Structure of a Particular Directory. 
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
