{% set name = "Directory-Tree" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rahulbordoloi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1c93a12f8a12ba36625bd2a72bad2ad49dbc8829274552fb4125bf3c7ca95aaa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - directory_tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rahulbordoloi/Directory-Tree/
  summary: Python Utility Package that displays out the Tree Structure of a Particular Directory.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
